name: CI/CD Pipeline
# Trigger the workflow on:
# 1. Any branch push
# 2. Pull requests to main
# 3. Tag creation starting with 'v'
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]
  create:
    tags: [ 'v*' ]

jobs:
  #Matrix Testing
  # Run tests across multiple Node.js versions to ensure compatibility
  
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Type Check
        run: npx tsc --noEmit
        
      - name: Build
        run: npm run build
        
      - name: Run tests
        run: npm test -- --watchAll=false --coverage
   # Perform various code quality checks including linting, secrets scanning, and SonarCloud     
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Lint
        run: npm run lint
        
      - name: Check for secrets
        uses: gitleaks/gitleaks-action@v2
        
      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 